version: "3.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ip_challenge_app
    volumes:
      - ./app:/app
    ports:
      - "3033:3000"

#  database:
#    image: postgres:14
#    container_name: clean_db
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=clean_db
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=clean_db
#    restart: always
#    ports:
#      - "5450:5432"