version: "3.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ip_challenge_app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3033:3000"
    depends_on:
      - database

  database:
    image: mongo:3.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=challenge
    volumes:
      - ./db/data:/data/db
    ports:
      - "27017:27017"

#  database:
#    image: postgres:14
#    container_name: clean_db
#    volumes:
#      - ./db/data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=clean_db
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=clean_db
#    restart: always
#    ports:
#      - "5450:5432"